# name: Commit

# on:
#   push:
#     branches:
#       - main
#   schedule:
#     - cron: "0 0 * * *"

# jobs:
#   autogreen:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Clone repository
#         uses: actions/checkout@v2

#       - name: Auto green
#         run: |
#           git config --local user.email "1273611131@qq.com"
#           git config --local user.name "LinChentang"
#           git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
#           git pull --rebase
#           git commit --allow-empty -m "a commit a day keeps your girlfriend away"
#           git push
